services:
    server:
        build: ./server
        volumes:
            - .:/server
        container_name: server
        restart: always
        environment:
            - PORT=5000
        command: ["deno", "run", "--watch", "--allow-net", "--allow-env", "--allow-read", "./src/main.ts"]

    client:
        build: ./client
        volumes:
            - .:/client
        container_name: client
        restart: always

    db:
        image: postgres:14.19-alpine3.21
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret_password
            POSTGRES_DB: weatheradvisor
        volumes:
            - ./init-scripts:/docker-entrypoint-initdb.d

    ollama:
        image: ollama/ollama:0.11.11
        volumes:
            - ./ollama/ollama:/root/.ollama
        container_name: ollama
        restart: always
        environment:
            - OLLAMA_KEEP_ALIVE=24h
            - OLLAMA_HOST=0.0.0.0
        entrypoint: ["/bin/sh", "-c"]
        command: >
            "ollama serve & sleep 3 && ollama pull tinyllama && wait"

    proxy:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - client
            - server